repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v1.8.0
      hooks:
      -   id: reorder-python-imports